// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'category': string;
  'content': string;
  'description': string;
  'font-headings': string;
  'font-headings-bold': string;
  'font-headings-secondary': string;
  'font-headings-secondary-bold': string;
  'font-large-headings-bold': string;
  'font-text-primary': string;
  'font-text-primary-bold': string;
  'font-text-secondary': string;
  'font-text-secondary-bold': string;
  'font-text-small': string;
  'font-text-small-bold': string;
  'highlight': string;
  'hover-transition': string;
  'icon': string;
  'result': string;
  'root': string;
  'row': string;
  'wrapper': string;
}
declare const cssExports: CssExports;
export = cssExports;
