// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'focused': string;
  'overlay': string;
  'root': string;
  'tooltip': string;
}
declare const cssExports: CssExports;
export = cssExports;
