// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'count': string;
  'searchEmpty': string;
  'searchInput': string;
  'searchPage': string;
  'searchResultWrapper': string;
}
declare const cssExports: CssExports;
export = cssExports;
