// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'filterItem': string;
  'searchFilters': string;
}
declare const cssExports: CssExports;
export = cssExports;
