// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'break-word': string;
  'copyLinkText': string;
  'font-headings': string;
  'font-headings-bold': string;
  'font-headings-secondary': string;
  'font-headings-secondary-bold': string;
  'font-large-headings-bold': string;
  'font-text-primary': string;
  'font-text-primary-bold': string;
  'font-text-secondary': string;
  'font-text-secondary-bold': string;
  'font-text-small': string;
  'font-text-small-bold': string;
  'hover-transition': string;
  'notFoundText': string;
  'searchEmpty': string;
  'searchQuery': string;
}
declare const cssExports: CssExports;
export = cssExports;
